### ISSUE TITLE
make the script take f*cking arguments n00b fag

### ISSUE THREAD

**Issue by LukaJankovic** [AxelMatstoms/abstractwallpaper#1]
title

**Comment by AxelMatstoms** [comment]
hey theres a reason its on github u fucking faggot branch it and do it yourself noob bitch. You're a lazy little bitch who wants everyone to serve you. ITS FUCKING OPEN SOURCE JUST DO IT YOURSELF XD

**Comment by LukaJankovic** [comment]
python iz shit u shud use assembly instead its better performans
